services:
  runejs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    volumes:
      - ./data:/usr/src/app/data
      - ./cache:/usr/src/app/cache
      - ./config:/usr/src/app/config
    ports:
      - "43591:43591"
      - "43592:43592"
      - "43594:43594"
    restart: always
